# Generated by Django 3.0.5 on 2020-04-09 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timeline', '0013_userfollowers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfollowers',
            name='followedUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
